import numpy as np
from scipy.spatial.transform import Rotation

from quadrotor_info import Quadrotor


class NominalPIDControllerDrone():
    """
    A PID controller for quadrotor position and attitude control.
    This class computes the required motor RPMs to drive the quadrotor
    to a desired 3D position.
    """
    def __init__(self,
                acceleration_gravity:float=9.81,
                time_step_size:float=1/240.
                ):
        """
        Initializes the PID controller.

        Args:
            acceleration_gravity (float, optional): The gravitational acceleration. Defaults to 9.81.
            time_step_size (float, optional): The simulation time step (dt). Defaults to 1/240.
        """
        
        self.agent : Quadrotor
        self.dt = time_step_size
        self.g = acceleration_gravity
        
        # Pre-compute the inverse of the RPM-to-Forces/Torques allocation matrix.
        # This matrix maps [Total Thrust, Torque_X, Torque_Y, Torque_Z] (scaled)
        # to the required (RPM^2) for each of the four motors.
        self.matrix_rpm2u_inv = np.linalg.inv(
            np.array([
                [1,   1,   1,   1],
                [-1,   1,   1,  -1],
                [1,  -1,   1,  -1], 
                [1,   1,  -1,   -1],
            ])
        )

    
    def thrust_from_rpm(self, motor_rpm:np.ndarray):
        """
        Calculates the thrust generated by each motor given its RPM.
        Thrust = k_f * (RPM)^2

        Args:
            motor_rpm (np.ndarray): Array of motor RPMs.

        Returns:
            np.ndarray: Thrust generated by each motor.
        """
        return self.agent.kf * np.square(motor_rpm)
        
        
    def rpm_from_thrust(self, motor_thrust:np.ndarray):
        """
        Calculates the required RPM to produce a given thrust.
        RPM = sqrt(Thrust / k_f)

        Args:
            motor_thrust (np.ndarray): Desired thrust from each motor.

        Returns:
            np.ndarray: Required RPM for each motor.
        """
        motor_rpm = motor_thrust / self.agent.kf
        motor_rpm[motor_rpm < 0.] = 0.  # Ensure non-negative thrust
        return np.sqrt(motor_rpm)
    
    
    def get_angular_position_error(self, 
                                   controlled_linear_acceleraion:np.ndarray,
                                   psi_ref:float=0.):
        """
        Computes the desired roll (phi) and pitch (theta) angles to
        achieve the desired linear acceleration.

        Args:
            controlled_linear_acceleraion (np.ndarray): The desired 3D acceleration
                                                       vector in the body frame.
            psi_ref (float, optional): The desired yaw (psi) angle. Defaults to 0.

        Returns:
            np.ndarray: A 3-element array of desired Euler angles [phi, theta, psi].
        """
        # Calculate desired roll and pitch from the components of the desired acceleration
        sine = np.sin(psi_ref)
        cosine = np.cos(psi_ref)
        phi_ref = np.arcsin(
            (controlled_linear_acceleraion[0]*sine - controlled_linear_acceleraion[1]*cosine)/
            (np.linalg.norm(controlled_linear_acceleraion) + 1e-6)  # Add epsilon to avoid division by zero
        )
        theta_ref = -np.arctan(
            (controlled_linear_acceleraion[0]*cosine + controlled_linear_acceleraion[1]*sine)/
            (controlled_linear_acceleraion[2] + 1e-6)  # Add epsilon to avoid division by zero
        )
        return np.array([phi_ref, theta_ref, psi_ref])
    

    def compute_PID_control(self,
                            agent:Quadrotor, 
                            target_linear_position:np.ndarray,
                            target_linear_velocity:np.ndarray=np.zeros(3),
                            target_linear_acceleration:np.ndarray=np.zeros(3),
                            ):
        """
        Computes the full cascaded PID control output (motor RPMs) for
        position and attitude control.

        Args:
            agent (Quadrotor): The quadrotor object to control, containing its current state.
            target_linear_position (np.ndarray): The desired 3D position [x, y, z].
            target_linear_velocity (np.ndarray, optional): The desired 3D velocity. Defaults to [0, 0, 0].
            target_linear_acceleration (np.ndarray, optional): The desired 3D acceleration (feed-forward). Defaults to [0, 0, 0].

        Returns:
            np.ndarray: A 4-element array of the computed RPMs for each motor.
        """
        
        self.agent = agent
        
        # --- Position PID Control (Outer Loop) ---
        # Calculate errors for the position controller
        linear_position_error = target_linear_position - self.agent.pos_states
        linear_velocity_error = target_linear_velocity - self.agent.d_pos_states
        
        # Update integral error
        self.agent.integral_position_error += linear_position_error * self.dt
        self.agent.prev_position_error = np.copy(linear_position_error)

        # Calculate desired linear acceleration from the position PID controller
        controlled_linear_acceleraion = (
            target_linear_acceleration +  # Feed-forward term
            self.agent.PID_coeffs_pos[0] * linear_position_error +               # Proportional
            self.agent.PID_coeffs_pos[1] * self.agent.integral_position_error +  # Integral
            self.agent.PID_coeffs_pos[2] * linear_velocity_error                 # Derivative
        )
        # Compensate for gravity
        controlled_linear_acceleraion[2] += self.g   
        
        # --- Attitude Control (Inner Loop) ---
        # Convert desired acceleration from world frame to the drone's body frame
        rot_matrix = Rotation.from_euler("xyz", self.agent.ang_states).as_matrix()
        controlled_linear_acceleraion = rot_matrix.T @ controlled_linear_acceleraion
        
        # Get desired [phi, theta, psi] angles from the desired body-frame acceleration
        angular_position_error = self.get_angular_position_error(controlled_linear_acceleraion)
        
        # Calculate errors for the attitude controller
        angular_velocity_error = (angular_position_error - self.agent.prev_angle_error) / self.dt
        self.agent.integral_angle_error += angular_position_error * self.dt
        self.agent.prev_angle_error = np.copy(angular_position_error)
        
        # Calculate desired angular acceleration from the attitude PID controller
        controlled_angular_acceleraion = (
            self.agent.PID_coeffs_ang[0] * angular_position_error +   # Proportional
            self.agent.PID_coeffs_ang[1] * self.agent.integral_angle_error + # Integral
            self.agent.PID_coeffs_ang[2] * angular_velocity_error     # Derivative
        )
        
        # --- Actuator Command Calculation ---
        # TLMN_scaled = [Total Thrust, Torque_X, Torque_Y, Torque_Z] (scaled)
        TLMN_scaled = np.zeros(4, dtype="float")
        
        # Calculate total thrust (T) required (scaled by k_f)
        TLMN_scaled[0] = self.agent.m * controlled_linear_acceleraion[2] / self.agent.kf
        
        # Calculate required torques (L, M, N) (scaled by k_f * L) -> Torque = I * angular_acceleration
        TLMN_scaled[1:] = self.agent.I @ controlled_angular_acceleraion / (self.agent.kf * self.agent.L)
        
        # Convert [T, L, M, N] to (RPM^2) for each motor using the inverse allocation matrix
        propellers_rpm_squared = (self.matrix_rpm2u_inv @ TLMN_scaled).squeeze()
        
        # Ensure no negative (RPM^2) values
        propellers_rpm_squared[propellers_rpm_squared < 0.] = 0.
        
        # Return the final RPM command
        return np.sqrt(propellers_rpm_squared)
