import numpy as np
from scipy.spatial.transform import Rotation
import matplotlib.pyplot as plt

from quadrotor_info import Quadrotor


class NominalPIDControllerDrone():
    """
    A PID controller for quadrotor position and attitude control.
    This class computes the required motor RPMs to drive the quadrotor
    to a desired 3D position.
    """
    def __init__(self,
                acceleration_gravity:float=9.81,
                time_step_size:float=1/240.
                ):
        """
        Initializes the PID controller.

        Args:
            acceleration_gravity (float, optional): The gravitational acceleration. Defaults to 9.81.
            time_step_size (float, optional): The simulation time step (dt). Defaults to 1/240.
        """
        
        self.agent : Quadrotor
        self.dt = time_step_size
        self.g = acceleration_gravity
        
        # History tracking for plotting
        self.rpm_history = {}  # Dictionary to store RPM history for each agent
        self.time_history = []
        
        # Pre-compute the inverse of the RPM-to-Forces/Torques allocation matrix.
        # This matrix maps [Total Thrust, Torque_X, Torque_Y, Torque_Z] (scaled)
        # to the required (RPM^2) for each of the four motors.
        self.matrix_rpm2u_inv = np.linalg.inv(
            np.array([
                [1,   1,   1,   1],
                [-1,   1,   1,  -1],
                [1,  -1,   1,  -1], 
                [1,   1,  -1,   -1],
            ])
        )


    
    def thrust_from_rpm(self, motor_rpm:np.ndarray):
        """
        Calculates the thrust generated by each motor given its RPM.
        Thrust = k_f * (RPM)^2

        Args:
            motor_rpm (np.ndarray): Array of motor RPMs.

        Returns:
            np.ndarray: Thrust generated by each motor.
        """
        return self.agent.kf * np.square(motor_rpm)
        
        
    def rpm_from_thrust(self, motor_thrust:np.ndarray):
        """
        Calculates the required RPM to produce a given thrust.
        RPM = sqrt(Thrust / k_f)

        Args:
            motor_thrust (np.ndarray): Desired thrust from each motor.

        Returns:
            np.ndarray: Required RPM for each motor.
        """
        motor_rpm = motor_thrust / self.agent.kf
        motor_rpm[motor_rpm < 0.] = 0.  # Ensure non-negative thrust
        return np.sqrt(motor_rpm)
    
    
    def get_angular_position_error(self, 
                                   controlled_linear_acceleration:np.ndarray,
                                   psi_ref:float=0.):
        """
        Computes the desired roll (phi) and pitch (theta) angles to
        achieve the desired linear acceleration.

        Args:
            controlled_linear_acceleration (np.ndarray): The desired 3D acceleration
                                                       vector in the body frame.
            psi_ref (float, optional): The desired yaw (psi) angle. Defaults to 0.

        Returns:
            np.ndarray: A 3-element array of desired Euler angles [phi, theta, psi].
        """
        # Calculate desired roll and pitch from the components of the desired acceleration
        sine = np.sin(psi_ref)
        cosine = np.cos(psi_ref)
        phi_ref = np.arcsin(
            (controlled_linear_acceleration[0]*sine - controlled_linear_acceleration[1]*cosine)/
            (np.linalg.norm(controlled_linear_acceleration) + 1e-6)  # Add epsilon to avoid division by zero
        )
        theta_ref = -np.arctan(
            (controlled_linear_acceleration[0]*cosine + controlled_linear_acceleration[1]*sine)/
            (controlled_linear_acceleration[2] + 1e-6)  # Add epsilon to avoid division by zero
        )
        return np.array([phi_ref, theta_ref, psi_ref])
    

    def compute_PID_control(self,
                            agent:Quadrotor, 
                            target_linear_position:np.ndarray,
                            target_linear_velocity:np.ndarray=np.zeros(3),
                            target_linear_acceleration:np.ndarray=np.zeros(3),
                            ):
        """
        Computes the full cascaded PID control output (motor RPMs) for
        position and attitude control.

        Args:
            agent (Quadrotor): The quadrotor object to control, containing its current state.
            target_linear_position (np.ndarray): The desired 3D position [x, y, z].
            target_linear_velocity (np.ndarray, optional): The desired 3D velocity. Defaults to [0, 0, 0].
            target_linear_acceleration (np.ndarray, optional): The desired 3D acceleration (feed-forward). Defaults to [0, 0, 0].

        Returns:
            np.ndarray: A 4-element array of the computed RPMs for each motor.
        """
        
        self.agent = agent
        
        # --- Position PID Control (Outer Loop) ---
        # Calculate errors for the position controller
        linear_position_error = target_linear_position - self.agent.pos_states
        linear_velocity_error = target_linear_velocity - self.agent.d_pos_states
        
        # Update integral error
        self.agent.integral_position_error += linear_position_error * self.dt
        self.agent.prev_position_error = np.copy(linear_position_error)

        # Calculate desired linear acceleration from the position PID controller
        controlled_linear_acceleration = (
            target_linear_acceleration +  # Feed-forward term
            self.agent.PID_coeffs_pos[0] * linear_position_error +               # Proportional
            self.agent.PID_coeffs_pos[1] * self.agent.integral_position_error +  # Integral
            self.agent.PID_coeffs_pos[2] * linear_velocity_error                 # Derivative
        )
        # Compensate for gravity
        controlled_linear_acceleration[2] += self.g   


        # --- Attitude Control (Inner Loop) ---
        # Convert desired acceleration from world frame to the drone's body frame
        rot_matrix = Rotation.from_euler("xyz", self.agent.ang_states).as_matrix()
        controlled_linear_acceleration = rot_matrix.T @ controlled_linear_acceleration

        print("Controlled linear acceleration:", controlled_linear_acceleration)
        
        # Get desired [phi, theta, psi] angles from the desired body-frame acceleration
        angular_position_error = self.get_angular_position_error(controlled_linear_acceleration)
        
        # Calculate errors for the attitude controller
        angular_velocity_error = (angular_position_error - self.agent.prev_angle_error) / self.dt
        self.agent.integral_angle_error += angular_position_error * self.dt
        self.agent.prev_angle_error = np.copy(angular_position_error)
        
        # Calculate desired angular acceleration from the attitude PID controller
        controlled_angular_acceleration = (
            self.agent.PID_coeffs_ang[0] * angular_position_error +   # Proportional
            self.agent.PID_coeffs_ang[1] * self.agent.integral_angle_error + # Integral
            self.agent.PID_coeffs_ang[2] * angular_velocity_error     # Derivative
        )
        
        print("Controlled angular acceleration:", controlled_angular_acceleration)

        # --- Actuator Command Calculation ---
        # TLMN_scaled = [Total Thrust, Torque_X, Torque_Y, Torque_Z] (scaled)
        TLMN_scaled = np.zeros(4, dtype="float")
        
        # Calculate total thrust (T) required (scaled by k_f)
        TLMN_scaled[0] = self.agent.m * controlled_linear_acceleration[2] / self.agent.kf
        
        # Calculate required torques (L, M, N) (scaled by k_f * L) -> Torque = I * angular_acceleration
        TLMN_scaled[1:] = self.agent.I @ controlled_angular_acceleration / (self.agent.kf * self.agent.L)
        
        # Convert [T, L, M, N] to (RPM^2) for each motor using the inverse allocation matrix
        propellers_rpm_squared = (self.matrix_rpm2u_inv @ TLMN_scaled).squeeze()
        
        # Ensure no negative (RPM^2) values
        propellers_rpm_squared[propellers_rpm_squared < 0.] = 0.
        
        # Return the final RPM command
        return np.sqrt(propellers_rpm_squared)
    
    def store_rpm_history(self, agent_id, ref_rpm, actual_rpm, time_step):
        """
        Store RPM history for plotting.
        
        Args:
            agent_id (int): The agent ID
            ref_rpm (np.ndarray): Reference RPM values
            actual_rpm (np.ndarray): Actual RPM values
            time_step (float): Current simulation time
        """
        if agent_id not in self.rpm_history:
            self.rpm_history[agent_id] = {
                'time': [],
                'ref_rpm': [[], [], [], []],  # 4 motors
                'actual_rpm': [[], [], [], []]  # 4 motors
            }
        
        self.rpm_history[agent_id]['time'].append(time_step)
        for i in range(4):
            self.rpm_history[agent_id]['ref_rpm'][i].append(ref_rpm[i])
            self.rpm_history[agent_id]['actual_rpm'][i].append(actual_rpm[i])
    
    def plot_rpm_history(self, agent_id):
        """
        Plot RPM history for a specific agent.
        
        Args:
            agent_id (int): The agent ID to plot
        """
        if agent_id not in self.rpm_history:
            print(f"No RPM history found for agent {agent_id}")
            return
        
        history = self.rpm_history[agent_id]
        time_array = np.array(history['time'])
        
        # Create subplots for each motor
        fig, axes = plt.subplots(2, 2, figsize=(12, 8))
        fig.suptitle(f'RPM History for Agent {agent_id}', fontsize=16)
        
        motors = ['Motor 1', 'Motor 2', 'Motor 3', 'Motor 4']
        positions = [(0, 0), (0, 1), (1, 0), (1, 1)]
        
        for i, (motor_name, pos) in enumerate(zip(motors, positions)):
            ax = axes[pos[0], pos[1]]
            ax.plot(time_array, history['ref_rpm'][i], 'b--', label='Reference RPM', linewidth=2)
            ax.plot(time_array, history['actual_rpm'][i], 'r-', label='Actual RPM', linewidth=1.5)
            ax.set_title(motor_name)
            ax.set_xlabel('Time (s)')
            ax.set_ylabel('RPM')
            ax.legend()
            ax.grid(True, alpha=0.3)
        
        plt.tight_layout()
        plt.show()
    
    def plot_all_agents_rpm(self):
        """
        Plot RPM comparison for all agents.
        """
        if not self.rpm_history:
            print("No RPM history found for any agents")
            return
        
        num_agents = len(self.rpm_history)
        fig, axes = plt.subplots(num_agents, 4, figsize=(16, 4*num_agents))
        if num_agents == 1:
            axes = axes.reshape(1, -1)
        
        fig.suptitle('RPM History Comparison - All Agents', fontsize=16)
        
        for agent_idx, agent_id in enumerate(sorted(self.rpm_history.keys())):
            history = self.rpm_history[agent_id]
            time_array = np.array(history['time'])
            
            for motor_idx in range(4):
                ax = axes[agent_idx, motor_idx]
                ax.plot(time_array, history['ref_rpm'][motor_idx], 'b--', label='Ref', linewidth=1.5)
                ax.plot(time_array, history['actual_rpm'][motor_idx], 'r-', label='Actual', linewidth=1)
                ax.set_title(f'Agent {agent_id} - Motor {motor_idx+1}')
                ax.set_xlabel('Time (s)')
                ax.set_ylabel('RPM')
                ax.legend(fontsize=8)
                ax.grid(True, alpha=0.3)
        
        plt.tight_layout()
        plt.show()
