import numpy as np
import pybullet_data
import pybullet as pb
from scipy.spatial.transform import Rotation

from quadrotor_info import Quadrotor


class PybulletHandler():
    """
    Manages all interactions with the PyBullet physics simulation.
    This class is responsible for setting up the environment,
    stepping the simulation, applying control inputs to agents,
    and reading their states back.
    """
    def __init__(self, 
                 acceleration_gravity:float,
                 time_step_size:float,
                ):
        """
        Initializes the PyBullet simulation environment.

        Args:
            acceleration_gravity (float): The gravitational acceleration (e.g., 9.81).
                                          Will be applied as a negative Z-axis force.
            time_step_size (float): The duration of a single simulation step (e.g., 1/240.0).
        """
        print("[PybulletHandler] Connecting to PyBullet simulation...")
        # Connect to the physics server. pb.GUI displays the simulation window.
        # pb.DIRECT would run headless (no GUI).
        pb.connect(pb.GUI)
        
        # Disable real-time simulation to allow for manual stepping
        pb.setRealTimeSimulation(0) 
        
        # Set the duration of each simulation step
        pb.setTimeStep(time_step_size)
        
        # Disable the default PyBullet GUI widgets (sliders, buttons)
        pb.configureDebugVisualizer(pb.COV_ENABLE_GUI, 0)
        
        # Add the default PyBullet assets (like 'plane.urdf') to the search path
        pb.setAdditionalSearchPath(pybullet_data.getDataPath())
        
        # Set the simulation's gravity
        pb.setGravity(0, 0, -acceleration_gravity)
        
        # Load a ground plane model
        pb.loadURDF("plane.urdf")

        self.t = 0.  # Simulation time counter
        self.dt = time_step_size
        print(f"[PybulletHandler] Environment initialized with time step {round(self.dt, 2)}s and gravity -{acceleration_gravity} m/s^2.")

    
    def update_states(self, agent : Quadrotor):
        """
        Fetches the current kinematic state (position, orientation, velocities)
        of a given agent from the PyBullet simulation and updates the agent's
        internal state variables.

        Args:
            agent (Quadrotor): The agent object (e.g., an instance of your Quadrotor class)
                               to be updated. Must have an `id` attribute.
        """
        # Get the 7D state (3D position + 4D quaternion orientation) from PyBullet
        position, orientation_quat = pb.getBasePositionAndOrientation(bodyUniqueId=agent.id)
        
        # Convert the quaternion [x, y, z, w] to Euler angles [roll, pitch, yaw]
        euler_angles = Rotation.from_quat(orientation_quat).as_euler('xyz')
        
        # `np.unwrap` prevents angle jumps (e.g., from +pi to -pi).
        agent.ang_states = np.unwrap([agent.ang_states, euler_angles], axis=0)[-1]
        
        # Update the agent's position
        agent.pos_states = np.array(position)
        
        # Get the 6D velocities (3D linear + 3D angular) from PyBullet
        linear_vel, angular_vel = pb.getBaseVelocity(bodyUniqueId=agent.id)
        
        # Update the agent's velocity states
        agent.d_ang_states = np.array(angular_vel)
        agent.d_pos_states= np.array(linear_vel)

    
    def apply_ctrl_inputs(self, agent : Quadrotor, rpm_cmd:np.ndarray):
        """
        Applies the calculated motor control inputs (RPMs) to the quadrotor
        model in the simulation. This function converts RPMs into forces and
        torques based on the agent's properties (kf, km).

        Args:
            agent (Quadrotor): The agent object to apply forces to.
            rpm_cmd (np.ndarray): A 4-element array of desired RPMs for each motor.
        """
        # --- Motor Model ---
        # Enforce RPM limits (cannot be negative or exceed max RPM)
        rpm_cmd = np.clip(rpm_cmd, 0., agent.max_rpm)
        
        # Calculate thrust force for each motor: F = k_f * (RPM)^2
        forces = np.square(rpm_cmd) * agent.kf
        
        # Calculate the torque generated by each motor: T = k_m * (RPM)^2
        torques = np.square(rpm_cmd) * agent.km
        
        # Calculate the net yaw torque (Z-axis)
        # Assumes motors 0 & 1 spin one way, 2 & 3 spin the other
        z_torque = (torques[0] + torques[1] - torques[2] - torques[3])
        
        # --- Apply Forces and Torques to Simulation ---
        # Note: The link indices (0, 1, 2, 3, 4) must match your URDF definition.
        # Here, it's assumed links 0-3 are for thrust and link 4 is the main body for yaw.
        
        # Apply thrust from motor 2 to link 0
        pb.applyExternalForce(
            agent.id,
            0,  # Link index 0
            forceObj=[0, 0, forces[2]],
            posObj=[0, 0, 0],
            flags=pb.LINK_FRAME,
        )
        # Apply thrust from motor 1 to link 1
        pb.applyExternalForce(
            agent.id,
            1,  # Link index 1
            forceObj=[0, 0, forces[1]],
            posObj=[0, 0, 0],
            flags=pb.LINK_FRAME,
        )
        # Apply thrust from motor 3 to link 2
        pb.applyExternalForce(
            agent.id,
            2,  # Link index 2
            forceObj=[0, 0, forces[3]],
            posObj=[0, 0, 0],
            flags=pb.LINK_FRAME,
        )
        # Apply thrust from motor 0 to link 3
        pb.applyExternalForce(
            agent.id,
            3,  # Link index 3
            forceObj=[0, 0, forces[0]],
            posObj=[0, 0, 0],
            flags=pb.LINK_FRAME,
        )
        # Apply the net yaw torque to the main body (link 4)
        pb.applyExternalTorque(
            agent.id,
            4,  # Link index 4 (main body)
            torqueObj=[0, 0, z_torque],
            flags=pb.LINK_FRAME,
        )
        
        
    def step_sim(self, agents_list:list, step_flag:bool=True):
        """
        Advances the simulation by one time step and updates the state
        of all agents.

        Args:
            agents_list (list): A list of all agent objects to be updated.
            step_flag (bool, optional): If True, advance the simulation. 
                                        Set to False if you only want to update states.
        """
        if step_flag:
            pb.stepSimulation()
            self.t += self.dt
        
        # Update the internal state of all agents to match the new simulation state
        for agent in agents_list: 
            self.update_states(agent)

        # --- Optional: Debug Camera ---
        # Uncomment this block to have the camera follow the first agent
        # if agents_list:
        #     pb.resetDebugVisualizerCamera(
        #         cameraDistance=1.5,
        #         cameraYaw=45,
        #         cameraPitch=-30,
        #         cameraTargetPosition=agents_list[0].pos_states
        #     )

    
    def quit(self):
        """
        Disconnects from the PyBullet simulation.
        """
        print("[PybulletHandler] Disconnecting from simulation.")
        pb.disconnect()
